/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as AlbumsIndexRouteImport } from './routes/albums/index'
import { Route as ClipsIndexRouteImport } from './routes/clips/index'
import { Route as ProtectedAlbumsNewRouteImport } from './routes/_protected/albums/new'
import { Route as ProtectedClipsNewRouteImport } from './routes/_protected/clips/new'
import { Route as AlbumsSlugIndexRouteImport } from './routes/albums/$slug/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBlobImageSplatRouteImport } from './routes/api/blob-image/$'
import { Route as ProtectedAlbumsSlugEditRouteImport } from './routes/_protected/albums/$slug/edit'
import { Route as ProtectedClipsIdUpdateRouteImport } from './routes/_protected/clips/$id/update'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const AlbumsIndexRoute = AlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsIndexRoute = ClipsIndexRouteImport.update({
  id: '/clips/',
  path: '/clips/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAlbumsNewRoute = ProtectedAlbumsNewRouteImport.update({
  id: '/albums/new',
  path: '/albums/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedClipsNewRoute = ProtectedClipsNewRouteImport.update({
  id: '/clips/new',
  path: '/clips/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const AlbumsSlugIndexRoute = AlbumsSlugIndexRouteImport.update({
  id: '/albums/$slug/',
  path: '/albums/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlobImageSplatRoute = ApiBlobImageSplatRouteImport.update({
  id: '/api/blob-image/$',
  path: '/api/blob-image/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAlbumsSlugEditRoute = ProtectedAlbumsSlugEditRouteImport.update({
  id: '/albums/$slug/edit',
  path: '/albums/$slug/edit',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedClipsIdUpdateRoute = ProtectedClipsIdUpdateRouteImport.update({
  id: '/clips/$id/update',
  path: '/clips/$id/update',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/albums/': typeof AlbumsIndexRoute
  '/clips/': typeof ClipsIndexRoute
  '/albums/new': typeof ProtectedAlbumsNewRoute
  '/clips/new': typeof ProtectedClipsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob-image/$': typeof ApiBlobImageSplatRoute
  '/albums/$slug/': typeof AlbumsSlugIndexRoute
  '/albums/$slug/edit': typeof ProtectedAlbumsSlugEditRoute
  '/clips/$id/update': typeof ProtectedClipsIdUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/albums': typeof AlbumsIndexRoute
  '/clips': typeof ClipsIndexRoute
  '/albums/new': typeof ProtectedAlbumsNewRoute
  '/clips/new': typeof ProtectedClipsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob-image/$': typeof ApiBlobImageSplatRoute
  '/albums/$slug': typeof AlbumsSlugIndexRoute
  '/albums/$slug/edit': typeof ProtectedAlbumsSlugEditRoute
  '/clips/$id/update': typeof ProtectedClipsIdUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/albums/': typeof AlbumsIndexRoute
  '/clips/': typeof ClipsIndexRoute
  '/_protected/albums/new': typeof ProtectedAlbumsNewRoute
  '/_protected/clips/new': typeof ProtectedClipsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob-image/$': typeof ApiBlobImageSplatRoute
  '/albums/$slug/': typeof AlbumsSlugIndexRoute
  '/_protected/albums/$slug/edit': typeof ProtectedAlbumsSlugEditRoute
  '/_protected/clips/$id/update': typeof ProtectedClipsIdUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/albums/'
    | '/clips/'
    | '/albums/new'
    | '/clips/new'
    | '/api/auth/$'
    | '/api/blob-image/$'
    | '/albums/$slug/'
    | '/albums/$slug/edit'
    | '/clips/$id/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/albums'
    | '/clips'
    | '/albums/new'
    | '/clips/new'
    | '/api/auth/$'
    | '/api/blob-image/$'
    | '/albums/$slug'
    | '/albums/$slug/edit'
    | '/clips/$id/update'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/register'
    | '/_protected/dashboard'
    | '/albums/'
    | '/clips/'
    | '/_protected/albums/new'
    | '/_protected/clips/new'
    | '/api/auth/$'
    | '/api/blob-image/$'
    | '/albums/$slug/'
    | '/_protected/albums/$slug/edit'
    | '/_protected/clips/$id/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  ClipsIndexRoute: typeof ClipsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlobImageSplatRoute: typeof ApiBlobImageSplatRoute
  AlbumsSlugIndexRoute: typeof AlbumsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof AlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips/': {
      id: '/clips/'
      path: '/clips'
      fullPath: '/clips/'
      preLoaderRoute: typeof ClipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/albums/new': {
      id: '/_protected/albums/new'
      path: '/albums/new'
      fullPath: '/albums/new'
      preLoaderRoute: typeof ProtectedAlbumsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/clips/new': {
      id: '/_protected/clips/new'
      path: '/clips/new'
      fullPath: '/clips/new'
      preLoaderRoute: typeof ProtectedClipsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/albums/$slug/': {
      id: '/albums/$slug/'
      path: '/albums/$slug'
      fullPath: '/albums/$slug/'
      preLoaderRoute: typeof AlbumsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blob-image/$': {
      id: '/api/blob-image/$'
      path: '/api/blob-image/$'
      fullPath: '/api/blob-image/$'
      preLoaderRoute: typeof ApiBlobImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/albums/$slug/edit': {
      id: '/_protected/albums/$slug/edit'
      path: '/albums/$slug/edit'
      fullPath: '/albums/$slug/edit'
      preLoaderRoute: typeof ProtectedAlbumsSlugEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/clips/$id/update': {
      id: '/_protected/clips/$id/update'
      path: '/clips/$id/update'
      fullPath: '/clips/$id/update'
      preLoaderRoute: typeof ProtectedClipsIdUpdateRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedAlbumsNewRoute: typeof ProtectedAlbumsNewRoute
  ProtectedClipsNewRoute: typeof ProtectedClipsNewRoute
  ProtectedAlbumsSlugEditRoute: typeof ProtectedAlbumsSlugEditRoute
  ProtectedClipsIdUpdateRoute: typeof ProtectedClipsIdUpdateRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedAlbumsNewRoute: ProtectedAlbumsNewRoute,
  ProtectedClipsNewRoute: ProtectedClipsNewRoute,
  ProtectedAlbumsSlugEditRoute: ProtectedAlbumsSlugEditRoute,
  ProtectedClipsIdUpdateRoute: ProtectedClipsIdUpdateRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  ClipsIndexRoute: ClipsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlobImageSplatRoute: ApiBlobImageSplatRoute,
  AlbumsSlugIndexRoute: AlbumsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
